lms/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    url(r'', include('website.urls')),
]

website/urls.py
from django.conf.urls import url

from .views import book_document, category_view, dashboard_view, document_edit_view, history_view, index_view, \
    manager_view, outstanding_request, renew_document, return_document, search_view, sign_in_view, sign_up_view, \
    sign_out_view, single_view, user_profile_view, api

urlpatterns = [
    url(r'^api/search/', api.api_search, name='api-search'),
    url(r'^$', index_view.index, name='index'),
    url('dashboard', dashboard_view.dashboard_view, name='dashboard'),
    url('history', history_view.history_view, name='history'),
    url('sign-in', sign_in_view.sign_in_view, name='sign-in'),
    url('sign-up', sign_up_view.sign_up_view, name='sign-up'),
    url('sign-out', sign_out_view.sign_out_view, name='sign-out'),
    url('single', single_view.single_view, name='single'),
    url('category', category_view.category_view, name='category'),
    url('user-profile', user_profile_view.user_profile_view, name='user-profile'),
    url(r'^books/(?P<doc_id>\d+)/$', single_view.single_view, name='single-view'),
    url('manager', manager_view.manager_view, name='manager'),
    url(r'^search/$', search_view.search_view, name='search'),
    url(r'^document/(?P<pk>\d+)/edit/$', document_edit_view.document_edit, name='document_edit'),
    url('api/book_document/(?P<doc_id>\d+)/$', book_document.book_document, name='book-document'),
    url('api/return_document/(?P<rec_id>\d+)/$', return_document.return_document, name='return-document'),
    url('api/renew_document/(?P<rec_id>\d+)/$', renew_document.renew_document, name='renew-document'),
    url('api/outstanding_request/(?P<doc_id>\d+)/$', outstanding_request.outstanding_request,
        name='outstanding-request'),

]

website/models/author.py
from django.db import models
from django.utils import timezone


class Author(models.Model):
    """Author model which stores information about """

    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    created_date = models.DateTimeField(
        default=timezone.now)

    def __str__(self):
        return self.first_name + " " + self.last_name

    class Meta:
        app_label = 'website'

website/models/av.py
from .document import Document


class AV(Document):
    """Audio/Video model is one of Document types"""
    type = Document.AV

website/models/base_model.py
from django.db import models
from django.utils import timezone


class BaseModel(models.Model):
    """Base model implements the most popular stuff"""
    title = models.CharField(max_length=250)
    created_date = models.DateTimeField(
        default=timezone.now)

    def __str__(self):
        return self.title

    class Meta:
        abstract = True
        app_label = 'website'

website/models/book.py
from django.db import models

from .document import Document


class Book(Document):
    """Books is one of Document types"""
    publisher = models.ForeignKey('website.Publisher', related_name='book_publisher', on_delete=models.CASCADE,
                                  null=True)
    issue = models.IntegerField(null=True)
    ISBN = models.CharField(max_length=17, default="")
    pages = models.IntegerField(null=True)
    type = Document.BOOK

    @property
    def reading_time_in_hours(self):
        # average speed of reading is 45-50 pages per hour
        return self.pages // 50 + 1

website/models/document.py
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.utils import timezone

from .record import Record
from .tag import Tag
from .author import Author
from .base_model import BaseModel


class Document(BaseModel):
    """Document model which is used for all types of documents stored in library."""
    is_reference = models.BooleanField(default=False)
    is_bestseller = models.BooleanField(default=False)
    authors = models.ManyToManyField(Author)
    tags = models.ManyToManyField(Tag)
    price = models.IntegerField(default=0)
    copies = models.IntegerField(default=0)
    description = models.TextField()
    published_date = models.DateTimeField(
        default=timezone.now)

    BOOK = 'BK'
    AV = 'AV'
    ARTICLES = 'AC'

    DOC_TYPES = (
        (BOOK, 'Book'),
        (AV, 'av'),
        (ARTICLES, 'JournalArticles'),
    )

    type = models.CharField(max_length=2, choices=DOC_TYPES, default=BOOK)

    def clean(self):
        """
            Validation for copies of check outed documents
        """
        q = Q(document=self) & (Q(status=Record.TAKEN) | Q(status=Record.RENEWED) | Q(status=Record.RETURNED))
        records = Record.objects.all().filter(q)
        if len(records) > self.copies:
            raise ValidationError(
                'Count of copies cannot be smaller than count of check outed books.')

    @property
    def img_src(self):
        """Virtual attribute for image source string"""
        return '/static/images/products/products-3.jpg'

website/models/journal.py
from django.db import models
from django.utils import timezone

from .author import Author
from .base_model import BaseModel


class Journal(BaseModel):
    """Journal use as a publish place in JournalArticles"""
    publisher = models.ForeignKey(
        'website.Publisher', related_name='journal_publisher', on_delete=models.CASCADE)
    issue = models.IntegerField()
    ISSN = models.CharField(max_length=17, default="")
    pages = models.IntegerField(null=True)
    editors = models.ManyToManyField(Author)
    published_date = models.DateTimeField(
        default=timezone.now)

website/models/journal_articles.py
from django.db import models

from .document import Document


class JournalArticles(Document):
    """JournalArticles is one of Document types"""
    journal = models.ForeignKey(
        'website.Journal', related_name='journal', on_delete=models.CASCADE, null=True)
    type = Document.ARTICLES

website/models/profile.py
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import Q
from django.utils import timezone
from django.utils.translation import gettext as _

from website.models.record import Record
from website.models.request import Request


class Profile(models.Model):
    """Model Profile is an extension of model User"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.TextField(max_length=150, blank=True)

    phone_regex = RegexValidator(regex=r'^\d{9,12}$',
                                 message=_("Phone number must be entered in the format: +79999999999"))
    phone_number = models.CharField(
        verbose_name=_('phone number'), validators=[phone_regex], max_length=13, null=True, unique=True)

    STUDENT = 1
    INSTRUCTOR = 2
    TEACHING_ASSISTANT = 3
    VISITING_PROFESSOR = 4
    PROFESSOR = 5
    LIBRARIAN = 6

    TYPE_TYPES = (
        (STUDENT, 'Student'),
        (INSTRUCTOR, 'Instructor'),
        (TEACHING_ASSISTANT, 'TA'),
        (VISITING_PROFESSOR, 'Visitng Professor'),
        (PROFESSOR, 'Professor'),
        (LIBRARIAN, 'Librarian')
    )

    type = models.IntegerField(choices=TYPE_TYPES, default=STUDENT)

    def __str__(self):
        """String representations of the Profile"""
        return self.user.first_name + ' ' + self.user.last_name

    @property
    def is_student(self):
        """Virtual attribute to check if the profile corresponds to the group 'Student' """
        return self.user.groups.filter(name='student').exists()

    @property
    def is_faculty(self):
        """Virtual attribute to check if the profile corresponds to the group 'Faculty' """
        return self.user.groups.filter(name='faculty').exists()

    @property
    def is_librarian(self):
        """Virtual attribute to check if the profile corresponds to the group 'Librarian' """
        return self.user.groups.filter(name='librarian').exists()

    @property
    def is_visiting_professor(self):
        """Virtual attribute to check if the profile corresponds to the group 'Visiting Professor' """
        return self.user.groups.filter(name="visiting professor").exists()

    def checkout_document(self, document):
        """Method to checkout a document

            Returns:    i.  False if the document cannot be checked out
                        ii. Newly create model Record instance if the document is checked out
        """

        # Q objects are used to construct argument for filter in db query
        q = Q(document=document, user=self.user) & (
                Q(status=Record.WAITING) | Q(
            status=Record.TAKEN) | Q(status=Record.RENEWED) | Q(status=Record.RETURNED))
        not_closed_yet = Record.objects.filter(q).exists()

        outstanding_request = Request.objects.filter(document=document, type=Request.OUTSTANDING_REQUEST).exists()
        if document.is_reference or outstanding_request or not_closed_yet:
            return False

        record = Record(user=self.user, document=document)
        record.save()

        # Close all BOOK_AVAILBALE requests on the current document
        for request in Request.objects.filter(user=self.user, document=document, type=Request.BOOK_AVAILABLE):
            request.is_open = False

        return record

    def return_document(self, document):
        """
            Method for returning the document
            If returned successfully status of the record changes to RETURNED
            The status of approved returned book changes to CLOSED
        """
        record = Record.objects.all().filter(
            Q(user=self.user, document=document, status=Record.TAKEN) | Q(user=self.user, document=document,
                                                                          status=Record.RENEWED)).first()

        if record is None:
            return False

        record.status = Record.RETURNED
        record.save()

        requests = Request.objects.filter(
            user=self.user, document=document)
        for request in requests:
            request.is_open = False

        return True

    def renew_document(self, document):
        """
            Method for renewing the document
            If returned successfully status of the record changes to RENEWED
        """

        # Construction of Q object for DB query which extracts only records able to be renewed
        # Consider all records with status TAKEN
        q = Q(status=Record.TAKEN)
        # For visiting professor type also add records with status RENEWED
        if self.is_visiting_professor:
            q = q | Q(status=Record.RENEWED)
        # Now we extract all records which are related to current document and user
        q = q & Q(document=document, user=self.user)

        # Consider an element from QuerySet
        record = Record.objects.all().filter(q).first()

        outstanding_request_exists = Request.objects.filter(document=document,
                                                            type=Request.OUTSTANDING_REQUEST).exists()

        if record is None or outstanding_request_exists:
            return False

        record.status = Record.RENEWED
        record.last_status_modified_date = timezone.now()
        record.save()
        return True

website/models/publisher.py
from .base_model import BaseModel


class Publisher(BaseModel):
    """Publisher is a company which publish some Documents"""
    def __str__(self):
        return self.title
    pass

website/models/tag.py
from django.db import models
from django.utils import timezone

from .base_model import BaseModel


class Tag(BaseModel):
    """Model of tags and keywords for documents """
    pass

website/forms.py
from django import forms

from .models.document import Document


class DocForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('title', 'published_date', 'copies', 'authors',
                  'is_reference', 'is_bestseller', 'description')

website/views/api.py
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt

from website.models.author import Author
from website.models.document import Document

from django.core.serializers import serialize

from website.models.tag import Tag


@csrf_exempt
def api_search(request):
    if request.method == "POST":
        query = request.POST.get('query', '')
        tag = request.POST.get('tag', False)
        tag_id = request.POST.get('tag_id', False)

        if tag:
            tag = Tag.objects.filter(title__icontains=tag).first()
            docs = Document.objects.filter(tags=tag)
            data = serialize('json', docs)

            return HttpResponse(data, content_type='application/json')

        if tag_id:
            tag = Tag.objects.filter(pk=tag_id).first()
            docs = Document.objects.filter(tags=tag)
            data = serialize('json', docs)

            return HttpResponse(data, content_type='application/json')

        if query is not None:

            if 'OR' in query:
                queries = query.split(' OR ')
                docs = Document.objects.filter(Q(title__icontains=queries[0]) | Q(title__icontains=queries[1]))
                authors = Author.objects.filter(Q(first_name__icontains=queries[0]) | Q(last_name__icontains=queries[1]) | Q(first_name__icontains=queries[1]) | Q(last_name__icontains=queries[0]))

                for auth in authors:
                    docs = docs.union(Document.objects.filter(authors=auth))
            elif 'AND' in query:
                queries = query.split(' AND ')
                docs = Document.objects.filter(Q(title__icontains=queries[0]) & Q(title__icontains=queries[1]))
                authors = Author.objects.filter(Q(first_name__icontains=queries[0]) & Q(last_name__icontains=queries[1]) | Q(first_name__icontains=queries[1]) & Q(last_name__icontains=queries[0]))

                for auth in authors:
                    docs = docs.union(Document.objects.filter(authors=auth))
            else:
                docs = Document.objects.filter(title__icontains=query)
                docs = (docs | Document.objects.filter(description__icontains=query))
                authors = Author.objects.filter(Q(first_name__icontains=query) | Q(last_name__icontains=query))

                for auth in authors:
                    docs = docs.union(Document.objects.filter(authors=auth))

        data = serialize('json', docs)

        return HttpResponse(data, content_type='application/json')
    else:
        return HttpResponse(serialize('json', Document.objects.all()), content_type='application/json')

website/views/book_document.py
from django.shortcuts import redirect

from ..models.record import Record
from ..models.request import Request


def book_document(request, doc_id=0):
    """Books a document (if possible) for the user and redirects to dashboard"""
    record = Record(user_id=request.user.id, document_id=doc_id)

    request.user.profile.checkout_document(record.document)

    return redirect('dashboard')

website/views/books_list.py
from django.shortcuts import render

from ..models.document import Document


def books_list(request):
    documents = Document.objects.order_by('created_date')
    return render(request, 'website/books_list.html', {'books': documents})

website/views/category_view.py
from django.shortcuts import render

from ..models.document import Document


def category_view(request):
    """Renders category page"""
    documents = Document.objects.all()
    return render(request, 'website/category.html', {'documents': documents})

website/views/dashboard_view.py
from django.shortcuts import render, redirect

from ..models.record import Record


def dashboard_view(request):
    """Renders dashboard view or redirects to sign-in if not authenticated"""
    if request.user.is_authenticated:

        records = Record.objects.all() \
            .filter(user_id=request.user.id).exclude(status=Record.CLOSED).order_by('created_date')

        return render(request, 'website/dashboard.html', {'records': records, 'title': "Checked out books"})
    else:
        return redirect('sign-in')

website/views/document_edit_view.py
from django.shortcuts import get_object_or_404, redirect, render

from ..forms import DocForm
from ..models.document import Document


def document_edit(request, pk):
    document = get_object_or_404(Document, pk=pk)
    if request.method == "POST":
        form = DocForm(request.POST, instance=document)
        if form.is_valid():
            document.save()
            return redirect('single-view', document.id)
    else:
        form = DocForm(instance=document)
    return render(request, 'website/document_edit.html', {'form': form})

website/views/edit_data.py
from django import forms


def editData(request):
    if request.method == 'POST':
        form = forms.ModelForm(request.POST, request.FILES)

    if form.is_valid():
        form.save()

website/templates/website/partials/category.html
<section class=" section">
    <!-- Container Start -->
    <div class="container">
        <div class="row">
            <div class="col-12">
                <!-- Section title -->
                <div class="section-title">
                    <h2>All Categories</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis, provident!</p>
                </div>

                <div class="row">
                    <!-- Category list -->
                    <div class="col-lg-3 offset-lg-0 col-md-5 offset-md-1 col-sm-6 col-6">
                        <div class="category-block">
                            <div class="header">
                                <i class="fa fa-laptop icon-bg-1"></i>
                                <h4>Electronics</h4>
                            </div>
                            <ul class="category-list">
                                <li><a href={% url "category" %}>Laptops <span>93</span></a></li>
                                <li><a href={% url "category" %}>Iphone <span>233</span></a></li>
                                <li><a href={% url "category" %}>Microsoft <span>183</span></a></li>
                                <li><a href={% url "category" %}>Monitors <span>343</span></a></li>
                            </ul>
                        </div>
                    </div> <!-- /Category List -->
                    <!-- Category list -->
                    <div class="col-lg-3 offset-lg-0 col-md-5 offset-md-1 col-sm-6 col-6">
                        <div class="category-block">
                            <div class="header">
                                <i class="fa fa-apple icon-bg-2"></i>
                                <h4>Restaurants</h4>
                            </div>
                            <ul class="category-list">
                                <li><a href={% url "category" %}>Cafe <span>393</span></a></li>
                                <li><a href={% url "category" %}>Fast food <span>23</span></a></li>
                                <li><a href={% url "category" %}>Restaurants <span>13</span></a></li>
                                <li><a href={% url "category" %}>Food Track<span>43</span></a></li>
                            </ul>
                        </div>
                    </div> <!-- /Category List -->
                    <!-- Category list -->
                    <div class="col-lg-3 offset-lg-0 col-md-5 offset-md-1 col-sm-6 col-6">
                        <div class="category-block">
                            <div class="header">
                                <i class="fa fa-home icon-bg-3"></i>
                                <h4>Real Estate</h4>
                            </div>
                            <ul class="category-list">
                                <li><a href={% url "category" %}>Farms <span>93</span></a></li>
                                <li><a href={% url "category" %}>Gym <span>23</span></a></li>
                                <li><a href={% url "category" %}>Hospitals <span>83</span></a></li>
                                <li><a href={% url "category" %}>Parolurs <span>33</span></a></li>
                            </ul>
                        </div>
                    </div> <!-- /Category List -->
                    <!-- Category list -->
                    <div class="col-lg-3 offset-lg-0 col-md-5 offset-md-1 col-sm-6 col-6">
                        <div class="category-block">
                            <div class="header">
                                <i class="fa fa-shopping-basket icon-bg-4"></i>
                                <h4>Shoppings</h4>
                            </div>
                            <ul class="category-list">
                                <li><a href={% url "category" %}>Mens Wears <span>53</span></a></li>
                                <li><a href={% url "category" %}>Accessories <span>212</span></a></li>
                                <li><a href={% url "category" %}>Kids Wears <span>133</span></a></li>
                                <li><a href={% url "category" %}>It & Software <span>143</span></a></li>
                            </ul>
                        </div>
                    </div> <!-- /Category List -->
                    <!-- Category list -->
                    <div class="col-lg-3 offset-lg-0 col-md-5 offset-md-1 col-sm-6 col-6">
                        <div class="category-block">
                            <div class="header">
                                <i class="fa fa-briefcase icon-bg-5"></i>
                                <h4>Jobs</h4>
                            </div>
                            <ul class="category-list">
                                <li><a href={% url "category" %}>It Jobs <span>93</span></a></li>
                                <li><a href={% url "category" %}>Cleaning & Washing <span>233</span></a></li>
                                <li><a href={% url "category" %}>Management <span>183</span></a></li>
                                <li><a href={% url "category" %}>Voluntary Works <span>343</span></a></li>
                            </ul>
                        </div>
                    </div> <!-- /Category List -->
                    <!-- Category list -->
                    <div class="col-lg-3 offset-lg-0 col-md-5 offset-md-1 col-sm-6 col-6">
                        <div class="category-block">
                            <div class="header">
                                <i class="fa fa-car icon-bg-6"></i>
                                <h4>Vehicles</h4>
                            </div>
                            <ul class="category-list">
                                <li><a href={% url "category" %}>Bus <span>193</span></a></li>
                                <li><a href={% url "category" %}>Cars <span>23</span></a></li>
                                <li><a href={% url "category" %}>Motobike <span>33</span></a></li>
                                <li><a href={% url "category" %}>Rent a car <span>73</span></a></li>
                            </ul>
                        </div>
                    </div> <!-- /Category List -->
                    <!-- Category list -->
                    <div class="col-lg-3 offset-lg-0 col-md-5 offset-md-1 col-sm-6 col-6">
                        <div class="category-block">
                            <div class="header">
                                <i class="fa fa-paw icon-bg-7"></i>
                                <h4>Pets</h4>
                            </div>
                            <ul class="category-list">
                                <li><a href={% url "category" %}>Cats <span>65</span></a></li>
                                <li><a href={% url "category" %}>Dogs <span>23</span></a></li>
                                <li><a href={% url "category" %}>Birds <span>113</span></a></li>
                                <li><a href={% url "category" %}>Others <span>43</span></a></li>
                            </ul>
                        </div>
                    </div> <!-- /Category List -->
                    <!-- Category list -->
                    <div class="col-lg-3 offset-lg-0 col-md-5 offset-md-1 col-sm-6 col-6">
                        <div class="category-block">
                            <div class="header">
                                <i class="fa fa-laptop icon-bg-8"></i>
                                <h4>Services</h4>
                            </div>
                            <ul class="category-list">
                                <li><a href={% url "category" %}>Cleaning <span>93</span></a></li>
                                <li><a href={% url "category" %}>Car Washing <span>233</span></a></li>
                                <li><a href={% url "category" %}>Clothing <span>183</span></a></li>
                                <li><a href={% url "category" %}>Business <span>343</span></a></li>
                            </ul>
                        </div>
                    </div> <!-- /Category List -->


                </div>
            </div>
        </div>
    </div>
    <!-- Container End -->
</section>

website/templates/website/partials/filterbar.html
<div class="col-md-3">
				<div class="category-sidebar">
					<div class="widget category-list">
	<h4 class="widget-header">All Category</h4>
	<ul class="category-list">
		<li><a href="category.html">Laptops <span>93</span></a></li>
		<li><a href="category.html">Iphone <span>233</span></a></li>
		<li><a href="category.html">Microsoft  <span>183</span></a></li>
		<li><a href="category.html">Monitors <span>343</span></a></li>
	</ul>
</div>

<div class="widget category-list">
	<h4 class="widget-header">Nearby</h4>
	<ul class="category-list">
		<li><a href="category.html">New York <span>93</span></a></li>
		<li><a href="category.html">New Jersy <span>233</span></a></li>
		<li><a href="category.html">Florida  <span>183</span></a></li>
		<li><a href="category.html">California <span>120</span></a></li>
		<li><a href="category.html">Texas <span>40</span></a></li>
		<li><a href="category.html">Alaska <span>81</span></a></li>
	</ul>
</div>

<div class="widget filter">
	<h4 class="widget-header">Show Produts</h4>
	<select>
		<option>Popularity</option>
		<option value="1">Top rated</option>
		<option value="2">Lowest Price</option>
		<option value="4">Highest Price</option>
	</select>
</div>

<div class="widget price-range">
	<h4 class="widget-header">Price Range</h4>
	<div class="block">
		<b>$10</b>
		<input id="ex2" type="text" class="span2" value="" data-slider-min="10" data-slider-max="1000" data-slider-step="5" data-slider-value="[250,450]"/>
		<b>$5000</b>
	</div>
</div>

<div class="widget product-shorting">
	<h4 class="widget-header">By Condition</h4>
	<div class="form-check">
	  <label class="form-check-label">
	    <input class="form-check-input" type="checkbox" value="">
	    Brand New
	  </label>
	</div>
	<div class="form-check">
	  <label class="form-check-label">
	    <input class="form-check-input" type="checkbox" value="">
	    Almost New
	  </label>
	</div>
	<div class="form-check">
	  <label class="form-check-label">
	    <input class="form-check-input" type="checkbox" value="">
	    Gently New
	  </label>
	</div>
	<div class="form-check">
	  <label class="form-check-label">
	    <input class="form-check-input" type="checkbox" value="">
	    Havely New
	  </label>
	</div>
</div>

				</div>
			</div>

website/templates/website/partials/footer.html
{% load static %}

<footer class="container pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-6 col-md">
            <small class="d-block mb-3 text-muted">Innopolis University © 2018</small>
        </div>
        <div class="col-6 col-md">
            <h5>About</h5>
            <p class="text-secondary">It is an open-source platform for managing library developed by Innopolis University students.</p>
        </div>
    </div>
</footer>

website/templates/website/partials/header.html
{% load static %}
<section>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <a class="ml-3 navbar-brand mr-md-auto" href={% url "index" %}>
            <img src="{% static 'images/logo.png' %}" class="img-responsive" alt="">
        </a>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark" href="{% url "index" %}">Home</a>
            <a class="p-2 text-dark" href="{% url "dashboard" %}">Dashboard</a>
            <a class="p-2 text-dark" href="{% url "user-profile" %}">Profile</a>
            <a class="p-2 text-dark" href="{% url "category" %}">Categories</a>
        </nav>
        {% if request.user.pk is None%}
            <a class="btn btn-outline" href="{% url "sign-in" %}">Sign in</a>
            <a class="btn btn-outline-primary" href="{% url "sign-up" %}">Sign up</a>
        {% else %}
            <a class="btn btn-outline" href="{% url "sign-out" %}">Sign out</a>
        {% endif %}
    </div>
</section>

website/templates/website/partials/search_form.html
<form class="container">
    <div class="row justify-content-md-center">
        <div class="col-9">
            <input type="text" id="search-form" class="form-control mb-2 form-control-lg" placeholder="Search...">
        </div>
    </div>

    <div class="row justify-content-md-center mb-3">
        <div class="col-9">
            {% for tag in tags %}
                <a>
                    <span class="badge badge-secondary tags" id="tag-{{tag.id}}">{{ tag.title }}</span>
                </a>
            {% endfor %}
        </div>
    </div>
</form>

website/templates/website/partials/sidebar.html
{% load static %}
<div class="sidebar col-3">
    <div class="widget user-dashboard-profile">
        <div class="profile-thumb mb-2">
            <img src="{% static 'images/user/user-thumb.jpg' %}" alt="" class="rounded-circle img-fluid">
        </div>
        <h5 class="text-center">{{ request.user.first_name }} {{ request.user.last_name }}</h5>
        <p class="text-center">{{ request.user.profile.get_type_display }}</p>
    </div>
    <div class="widget user-dashboard-menu">
        <ul class="list-group">
            <a href="{% url 'dashboard' %}" class="list-group-item list-group-item-action"><i class="fa fa-user"></i> My Books</a>
            <a href="{% url 'history' %}" class="list-group-item list-group-item-action"><i class="fa fa-history"></i> History</a>
            <a href="{% url 'user-profile' %}" class="list-group-item list-group-item-action"><i class="fa fa-bookmark-o"></i> Favourite Books<span>5</span></a>
            <a href="{% url 'sign-out' %}" class="list-group-item list-group-item-action"><i class="fa fa-power-off"></i> Logout</a></li>
        </ul>
    </div>
</div>